### ISSUE TITLE
Banner on home page

### ISSUE THREAD

**Issue by kviviers** [benbillbob/gfsg#1]
Please re-size the banner to the same width as the text, slow the image transition, add ability to add a hyperlink for each image and enable forward and back selection by the user.

**Comment by benbillbob** [comment]
fixed with 310ed985f94b64984644aaf3b8b794de64a7040c

**Comment by kviviers** [comment]
Can we make the images links? eg I have put mindcamp on there and it would be great to make the image clickable for more info.

**Comment by benbillbob** [comment]
Click to edit the image, then you can set the HTMLLink


Sent from Mail for Windows 10
