### ISSUE TITLE
Email confirmation on registration

### ISSUE THREAD

**Issue by kviviers** [benbillbob/gfsg#2]
I registered a testaccount today but didn't receive any email confirmation. 

Welcome!

Thank you for registering with GFSG Inc. You have been added to our mailing list. 

GFSG Inc is a not for profit association designed to support families and teachers of gifted children. To view the benefits and to become a member please sign in to our site at LINK and select PAGENAME. There are 3 types of membership – Full membership, Professional membership and School Membership.

GFSG Committee.
www.gfsg.org.au

[unsubscribe message?]

**Comment by benbillbob** [comment]
You should be able to configure this on the register page.





Sent from Mail for Windows 10

From: kviviers
Sent: Tuesday, 15 August 2017 10:21 AM
To: benbillbob/gfsg
Cc: Subscribed
Subject: [benbillbob/gfsg] Email confirmation on registration (#2)

I registered a testaccount today but didn't receive any email confirmation.
Welcome!
Thank you for registering with GFSG Inc. You have been added to our mailing list.
GFSG Inc is a not for profit association designed to support families and teachers of gifted children. To view the benefits and to become a member please sign in to our site at LINK and select PAGENAME. There are 3 types of membership – Full membership, Professional membership and School Membership.
GFSG Committee.
www.gfsg.org.au
[unsubscribe message?]

**Comment by kviviers** [comment]
I have modified the wording and checked the settings (send confirmation is on) but no email being received. Do we need to configure an email send somewhere?

**Comment by benbillbob** [comment]
I think I missed a bit of back end email setup. I have emails coming out of my unit tests now for the tickets. I will double check this soon.

**Comment by benbillbob** [comment]
This appears to be working now.
